AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create global tables

Parameters:
  
  EnvType:
    Description: 'Environment: dev,qa,stg,prod'
    Type: String
    Default: prod
    AllowedValues:
    - dev
    - qa
    - stg
    - prod
    ConstraintDescription: must be either 'dev','qa','stg' or 'prod'

Resources:

  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is AlertPreference
  #-----------------------------------------------------------------------------

  AlertPreference:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - AlertPreference
      AttributeDefinitions:
        - AttributeName: PreferenceID
          AttributeType: S
        - AttributeName: AccountNumber
          AttributeType: S
        - AttributeName: DivisionCode
          AttributeType: S
      KeySchema:
        - AttributeName: PreferenceID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AccountNumber-DivisionCode-Index
          KeySchema:
            - AttributeName: AccountNumber
              KeyType: HASH
            - AttributeName: DivisionCode
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Ref AWS::Region
        - Region: us-west-1
  
  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is Elevate.Telematics.OTG
  #-----------------------------------------------------------------------------
  
  ElevateTelematicsOTG:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - elevate.telematics.OTG
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1

  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is telematics
  #-----------------------------------------------------------------------------
  
  telematicsdynamodb:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - telematics
      AttributeDefinitions:
        - AttributeName: DeviceIdentifier
          AttributeType: S
        - AttributeName: ReportDate
          AttributeType: S
      KeySchema:
        - AttributeName: DeviceIdentifier
          KeyType: HASH
        - AttributeName: ReportDate
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1

  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is telematics.alert
  #-----------------------------------------------------------------------------
  
  TelematicsAlert:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - telematics.alert
      AttributeDefinitions:
        - AttributeName: customerDivision
          AttributeType: S
        - AttributeName: triggeredTime
          AttributeType: S
      KeySchema:
        - AttributeName: customerDivision
          KeyType: HASH
        - AttributeName: triggeredTime
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1
  
  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is telematics.alertPreference
  #-----------------------------------------------------------------------------

  TelematicsalertPreference:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - telematics.alertPreference
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1
  
  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is Telematics.Equipmentlocations
  #-----------------------------------------------------------------------------
  
  TelematicsEquipmentlocations:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - telematics.equipmentlocations
      AttributeDefinitions:
        - AttributeName: EquipmentIdentifier
          AttributeType: S
      KeySchema:
        - AttributeName: EquipmentIdentifier
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1

  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is Telematics.Geofence
  #-----------------------------------------------------------------------------
  
  Telematicsgeofence:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - telematics.geofence
      AttributeDefinitions:
        - AttributeName: geofenceId
          AttributeType: S
      KeySchema:
        - AttributeName: geofenceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1

  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is Telematics.Geofence.AlertPreference
  #-----------------------------------------------------------------------------
  
  TelematicsGeofenceAlertPreference:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - telematics.geofence.alertPreference
      AttributeDefinitions:
        - AttributeName: geofenceId
          AttributeType: S
      KeySchema:
        - AttributeName: geofenceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1

  #-----------------------------------------------------------------------------
  # This DynamoDB Table Name is appsync-api-listing
  #-----------------------------------------------------------------------------
  
  AppsyncApilisting:
    Type: 'AWS::DynamoDB::GlobalTable'
    DeletionPolicy: Retain
    Properties:
      TableName:
        'Fn::Join':
            - '-'
            - - Ref: EnvType
              - appsync-api-listing
      AttributeDefinitions:
        - AttributeName: method_alias_name
          AttributeType: S
      KeySchema:
        - AttributeName: method_alias_name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: "KMS"
      Replicas:
        - Region: !Join [ "", [!Ref "AWS::Region"]]
        - Region: us-west-1
